# Generated by Django 2.0.7 on 2020-01-09 12:16

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('tel', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, unique=True)),
                ('DOB', models.DateField()),
                ('password', models.CharField(max_length=32)),
                ('Resume', models.FileField(upload_to="{%static 'static/images' %}")),
                ('gender', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
