# Generated by Django 2.0.7 on 2020-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200109_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_table',
            name='Resume',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
